# Preliminaries

In [1]:
import torch
import os
import pandas as pd
import numpy as np
from torch.distributions import multinomial

## Data manipulation

In [2]:
x = torch.arange(12)

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
torch.randn(3, 4)

tensor([[-0.9421, -0.4363,  0.2139,  0.9465],
        [ 0.4176,  0.6772, -2.1914,  0.1841],
        [-1.1750, -0.3570, -0.3404, -0.0956]])

In [8]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
x = torch.tensor([1, 2, 4.0])
y = torch.tensor([2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([3., 4., 6.]),
 tensor([-1.,  0.,  2.]),
 tensor([2., 4., 8.]),
 tensor([0.5000, 1.0000, 2.0000]),
 tensor([ 1.,  4., 16.]))

In [10]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 54.5982])

In [11]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [12]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
X.sum()

tensor(66.)

In [15]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [16]:
X[1, 2] = 9

In [17]:
X[:2, :] = 12

In [18]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [19]:
before = id(Y)
Y += X
id(Y) == before

True

In [20]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [21]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Linear alegbra

In [22]:
x = torch.arange(4)
x[3]

tensor(3)

In [23]:
len(x)

4

In [24]:
A = torch.arange(20).reshape(5, 4)

In [25]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [26]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [27]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [28]:
x = torch.arange(4, dtype=torch.float32)
x.sum()

tensor(6.)

In [29]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [30]:
A.sum(axis=[0, 1])

tensor(190.)

In [31]:
A.sum()

tensor(190.)

In [32]:
A.sum(axis=1, keepdims=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [33]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [34]:
y = torch.ones(4)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [35]:
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [36]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [37]:
u = torch.tensor([3., -4.])
torch.norm(u) # L2 norm

tensor(5.)

In [38]:
torch.norm(torch.ones(4, 9)) # Frobenius norm

tensor(6.)

## Automatic differentiation

In [39]:
x = torch.arange(4.0)

In [40]:
x.requires_grad_(True)
x.grad

In [41]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [42]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [43]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [44]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [45]:
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [46]:
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [47]:
x.grad.zero_()
y = x * x
z = y * x
z.sum().backward()
x.grad == 3 * x ** 2

tensor([True, True, True, True])

## Probability

In [48]:
fair_probs = torch.ones(6) / 6
fair_probs

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])

In [49]:
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 1., 0., 0., 0.])

In [50]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([2., 2., 2., 1., 2., 1.])

In [51]:
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000

tensor([0.1560, 0.1750, 0.1540, 0.1770, 0.1640, 0.1740])