# Preliminaries

In [ ]:
import torch

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [7]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn(3, 4)

tensor([[-0.0228, -0.3829, -0.0476,  1.2616],
        [-0.7867,  0.8431,  1.0652,  1.1040],
        [ 1.6055,  1.4552,  1.2031,  0.0859]])

In [10]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
x = torch.tensor([1, 2, 4.0])
y = torch.tensor([2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([3., 4., 6.]),
 tensor([-1.,  0.,  2.]),
 tensor([2., 4., 8.]),
 tensor([0.5000, 1.0000, 2.0000]),
 tensor([ 1.,  4., 16.]))

In [12]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 54.5982])

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [16]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum()

tensor(66.)

In [19]:
X.sum(dim=1)

tensor([ 6., 22., 38.])

In [21]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [24]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [25]:
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y
print(id(Z))

140390813445376
140390813445376


In [26]:
before = id(Y)
Y += X
id(Y) == before

True

In [27]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [29]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column names
    f.write('NA,Pave,127500\n') # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [30]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [31]:
inputs, outputs = data.iloc[:, :2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


<ipython-input-31-d780d07ac083>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [32]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [33]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [34]:
x = torch.arange(4)
x[3]

tensor(3)

In [35]:
len(x)

4

In [36]:
x.shape

torch.Size([4])

In [38]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [39]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [40]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [41]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [58]:
x = torch.arange(4, dtype=torch.float32)
x.sum()

tensor(6.)

In [44]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [45]:
A.sum(dim=0)

tensor([40., 45., 50., 55.])

In [46]:
A.sum(axis=[0, 1])

tensor(190.)

In [47]:
A.sum()

tensor(190.)

In [48]:
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [49]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [50]:
A.sum(axis=1, keepdims=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [51]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [52]:
x

tensor([0, 1, 2, 3])

In [59]:
y = torch.ones(4)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [60]:
A.shape, x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [61]:
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [62]:
torch.mm(A, x)

RuntimeError: mat2 must be a matrix

In [63]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [64]:
u = torch.tensor([3., -4.])
torch.norm(u) # L2 norm

tensor(5.)

In [66]:
torch.norm(torch.ones(4, 9)) # Frobenius norm

tensor(6.)

In [67]:
import numpy as np

In [68]:
def f(x):
    return 3 * x ** 2 - 4 * x

In [73]:
def numerical_limit(f, x, h):
    return (f(x + h) - f(x)) / h

In [74]:
h = 0.1
for i in range(5):
    print(numerical_limit(f, 1, h))
    h *= 0.1

2.3000000000000043
2.029999999999976
2.0029999999993104
2.000299999997956
2.0000300000155837


In [75]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [77]:
x.requires_grad_(True)
x.grad

In [78]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [79]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [80]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [81]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [82]:
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [84]:
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([ True, False, False, False])

In [87]:
x.grad.zero_()
y = x * x
z = y * x
z.sum().backward()
x.grad == 3 * x ** 2

tensor([True, True, True, True])

In [88]:
from torch.distributions import multinomial

In [92]:
fair_probs = torch.ones(6) / 6
fair_probs

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])

In [94]:
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 0., 0., 0., 1.])

In [95]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([1., 1., 3., 1., 2., 2.])

In [96]:
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000

tensor([0.1620, 0.1580, 0.1640, 0.1840, 0.1600, 0.1720])